/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:a4cd36fa-e2a3-4f18-b4f6-2eb5ef2412e8",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_wQeIBw5JX",
    "aws_user_pools_web_client_id": "7kspuo9furq1lsmucvj4c40agh",
    "oauth": {}
};


export default awsmobile;
